language: python

python:
  - "3.5.5"

services: postgresql

addons:
  postgresql: "9.6"

env:
  - DATABASE_URL=postgres://postgres:@localhost/travisci
  - TEST_DATABASE_URL=postgres://postgres:@localhost/test_travisci

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

before_script:
  - psql -c 'create database travisci;' -U postgres
  - psql -c 'create database test_travisci;' -U postgres
  - python manage.py db migrate
  - python manage.py db upgrade

script:
  - py.test --cov=app && coverage report

after_success:
    - coveralls