language: python

python:
  - "3.5.5"

addons:
  postgresql: "9.6" # prod server uses 10.6 which = dev server

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres:@localhost/test_travisci
    - SECRET='neither a particularly strong nor recommended secret is this now??'

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

before_script:
  - psql -c 'create database test_travisci;' -U postgres

script:
  - py.test --cov=app && coverage report

after_success:
    - coveralls
