"""Create MembershipClass

Revision ID: 1dafc4fd3d30
Revises: 83185df93823
Create Date: 2019-04-10 17:45:44.646606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dafc4fd3d30'
down_revision = '83185df93823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.String(length=75), nullable=True),
    sa.Column('lastModifiedOn', sa.DateTime(), nullable=False),
    sa.Column('lastModifiedBy', sa.String(length=75), nullable=True),
    sa.Column('class_name', sa.String(length=75), nullable=False),
    sa.Column('monthly_contrib_amount', sa.Float(precision=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('member', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'member', 'membership_class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_member_class_id_membership_class', 'member', type_='foreignkey')
    op.drop_column('member', 'class_id')
    op.drop_table('membership_class')
    # ### end Alembic commands ###
