"""Add lastLoggedIn, lastLoggedOut to Superusers

Revision ID: 3c7be6323422
Revises: 9b5d59f1c32b
Create Date: 2019-03-10 02:38:04.678468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7be6323422'
down_revision = '9b5d59f1c32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('super_user', sa.Column('lastLoggedIn', sa.DateTime(), nullable=False))
    op.add_column('super_user', sa.Column('lastLoggedOut', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('super_user', 'lastLoggedOut')
    op.drop_column('super_user', 'lastLoggedIn')
    # ### end Alembic commands ###
