"""Add rms-specifc properties to member

Revision ID: 6904ff5a13f3
Revises: 1dafc4fd3d30
Create Date: 2019-05-07 23:37:59.195046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6904ff5a13f3'
down_revision = '1dafc4fd3d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column(
                                'DateAccountActivated', 
                                sa.DateTime(), 
                                nullable=False,
                                server_default="2000-Jan-01 01:01:01"
                            )
    )
    op.add_column('member', sa.Column(
                                'accountActivated', 
                                sa.Boolean(), 
                                nullable=False,
                                server_default='False'
                            )
    )
    op.add_column('member', sa.Column('username', sa.String(length=75), nullable=True))
    op.alter_column('member', 'public_id',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # op.create_unique_constraint(op.f('uq_member_email'), 'member', ['email'])
    op.create_unique_constraint(op.f('uq_member_public_id'), 'member', ['public_id'])
    op.create_unique_constraint(op.f('uq_member_username'), 'member', ['username'])
    # op.drop_constraint('member_email_key', 'member', type_='unique')
    op.create_unique_constraint(op.f('uq_super_user_username'), 'super_user', ['username'])
    op.drop_constraint('super_user_username_key', 'super_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('super_user_username_key', 'super_user', ['username'])
    op.drop_constraint(op.f('uq_super_user_username'), 'super_user', type_='unique')
    # op.create_unique_constraint('member_email_key', 'member', ['email'])
    op.drop_constraint(op.f('uq_member_username'), 'member', type_='unique')
    op.drop_constraint(op.f('uq_member_public_id'), 'member', type_='unique')
    # op.drop_constraint(op.f('uq_member_email'), 'member', type_='unique')
    op.alter_column('member', 'public_id',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('member', 'username')
    op.drop_column('member', 'accountActivated')
    op.drop_column('member', 'DateAccountActivated')
    # ### end Alembic commands ###
