"""Create members table

Revision ID: 83185df93823
Revises: 3c7be6323422
Create Date: 2019-03-16 15:38:32.632721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83185df93823'
down_revision = '3c7be6323422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.String(length=75), nullable=True),
    sa.Column('lastModifiedOn', sa.DateTime(), nullable=False),
    sa.Column('lastModifiedBy', sa.String(length=75), nullable=True),
    sa.Column('public_id', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('lastLoggedIn', sa.DateTime(), nullable=False),
    sa.Column('lastLoggedOut', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=75), nullable=False),
    sa.Column('middle_name', sa.String(length=75), nullable=True),
    sa.Column('last_name', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('phone_number', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
