"""Create super user

Revision ID: 9b5d59f1c32b
Revises: 
Create Date: 2019-02-16 17:31:16.241638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5d59f1c32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.String(length=75), nullable=True),
    sa.Column('lastModifiedOn', sa.DateTime(), nullable=False),
    sa.Column('lastModifiedBy', sa.String(length=75), nullable=True),
    sa.Column('username', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('super_user')
    # ### end Alembic commands ###
